### PR TITLE
Adding Registration Feature

### PR DESCRIPTION
**Pull request by Mau-MD**
**Context**
The app doesn't have a registration feature yet. It has the endpoints, but there is not persistence nor ui to register

**This PR**
This PR adds the User Registration UI and calls the registration API to perform it

**Next**
Add the login UI and user persistence.

CleanShot 2022-07-11 at 16 25 27@2x

CleanShot 2022-07-11 at 16 26 00@2x

### CODE REVIEW

**Comment by nosoyilse** [comment]
Great work! 

I would split his PR into 2, login and registration! This would make it easier for reviewers! 

Same as before include more context in the PR about the project and plan!

**Comment by Mau-MD** [comment]
Done! Will open the next PR as soon as this one gets approved

**Comment by Mau-MD** [comment]
@nosoyilse made this PR smaller

**Review by nosoyilse — APPROVED** [review]
Looks good! It is better to not include components that are not going to use, like the index component :)

**Pull request merged**
